# fly.toml app configuration file generated for companion-memory on 2025-07-08T14:16:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'companion-memory'
primary_region = 'sea'

[build]

[deploy]
  strategy = "bluegreen"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[http_service.checks]]
  # Smoke test. Best used in conjunction with `deploy.strategy =
  # bluegreen`. The endpoint should validate that the newly-deployed
  # service is viable before swapping blue and green.
  path = "/"
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "10s"
